- hosts: all
  become: yes
  
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    containerd_device: "/dev/sdb"
    containerd_mount_point: "/var/lib/containerd-storage"
    containerd_original: "/var/lib/containerd"

    # Application deployment variables
    docker_registry_user: "skuuun"
    frontend_image_name: "t-nsa-frontend"
    backend_image_name: "t-nsa-backend"

    # Database configuration
    database_host: "192.168.2.12"
    database_port: "5432"
    database_type: "postgresql"
    database_name: "myapp_db"
    database_user: "myapp_user"
    database_password: "SecurePassword123!"

  tasks:
    - name: Install CENTOS utils
      include_tasks: ../tasks/install_CENTOS_utils.yml

    - name: Install Kubernetes
      include_tasks: ../tasks/install_k8s_centos.yml

    - name: Setup cluster
      include_tasks: ../tasks/setup_cluster.yml

    - name: Setup Rancher Local Path Provisioner
      include_tasks: ../tasks/setup_rancher_local_path_provisioner.yml

    - name: Install helm
      include_tasks: ../tasks/install_helm.yml

    - name: Install MetalLB
      include_tasks: ../tasks/install_metallb.yml

    - name: Configure certmanager
      include_tasks: ../tasks/install_cert_manager.yml

    - name: Configure gateway
      include_tasks: ../tasks/configure_k8s_gateway.yml

    - name: Configure dashboard
      include_tasks: ../tasks/configure_k8s_dashboard.yml

    # Install Gitea
    - name: Install Gitea
      include_tasks: ../tasks/install_gitea.yml

    - name: Deploy applications
      include_tasks: ../tasks/deploy_applications.yml