- hosts: all
  become: yes
  
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    containerd_device: "/dev/sdb"
    containerd_mount_point: "/var/lib/containerd-storage"
    containerd_original: "/var/lib/containerd"

  tasks:
    - name: Install CENTOS utils
      include_tasks: ../tasks/install_CENTOS_utils.yml

    - name: Install Kubernetes
      include_tasks: ../tasks/install_k8s_centos.yml

    - name: Setup cluster
      include_tasks: ../tasks/setup_cluster.yml

    - name: Setup Rancher Local Path Provisioner
      include_tasks: ../tasks/setup_rancher_local_path_provisioner.yml

    - name: Install helm
      include_tasks: ../tasks/install_helm.yml

    - name: Configure certmanager
      include_tasks: ../tasks/install_cert_manager.yml

    - name: Configure gateway
      include_tasks: ../tasks/configure_k8s_gateway.yml

    - name: Configure dashboard
      include_tasks: ../tasks/configure_k8s_dashboard.yml

    # Setup Gitea resources before installation
    - name: Setup Gitea resource directories and files
      include_tasks: ../tasks/setup_gitea_resources.yml

    # Install Gitea
    - name: Install Gitea
      include_tasks: ../tasks/install_gitea.yml