- hosts: all
  become: yes
  
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    containerd_device: "/dev/sdb"
    containerd_mount_point: "/var/lib/containerd-storage"
    containerd_original: "/var/lib/containerd"

  tasks:
    - name : Install CENTOS utils
      include_tasks: ../tasks/install_CENTOS_utils.yml

    - name: Install Kubernetes
      include_tasks: ../tasks/install_k8s_centos.yml

    - name: Setup cluster
      include_tasks: ../tasks/setup_cluster.yml

    - name: Install helm
      include_tasks: ../tasks/install_helm.yml

    - name: Configure gateway
      include_tasks: ../tasks/configure_k8s_gateway.yml

    - name: Configure dashboard
      include_tasks: ../tasks/configure_k8s_dashboard.yml
    
    - name: Install gitea
      include_tasks: ../tasks/install_gitea.yml