- hosts: all
  become: yes
  
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
    - name : Install CENTOS utils
      include_tasks: ../tasks/install_CENTOS_utils.yml

    - name: Install Kubernetes
      include_tasks: ../tasks/install_kubectl.yml