- hosts: all
  become: yes
  
  vars:
    ansible_python_interpreter: /root/.pyenv/shims/python3.12
    containerd_device: "/dev/sdb"
    containerd_mount_point: "/var/lib/containerd-storage"
    containerd_original: "/var/lib/containerd"

    # Database configuration variables
    postgres_root_password: "admin123"
    gitea_db_name: "gitea"
    gitea_db_user: "gitea"
    gitea_db_password: "gitea_secure_password_2024"
    app_db_name: "myapp_db"
    app_db_user: "myapp_user"
    app_db_password: "SecurePassword123!"

  tasks:
    - name: Install CENTOS utils
      include_tasks: ../tasks/install_CENTOS_utils.yml

    - name: Install and configure MySQL (simplified)
      include_tasks: ../tasks/install_psql.yml

    - name: Configure PostgreSQL for Gitea (simplified)
      include_tasks: ../tasks/configure_psql_gitea.yml

    - name: Configure PostgreSQL for application
      include_tasks: ../tasks/configure_psql_app.yml