- hosts: all
  become: yes
  vars_files:
    - ../network_vars.yml

  vars:
    ansible_python_interpreter: /usr/local/bin/python

  tasks:
    - name : Install BSD utils
      include_tasks: ../tasks/install_BSD_utils.yml
      
    - name: Setup the DNS server
      include_tasks: ../tasks/setup_dns_server.yml

    - name: Setup the dhcp server
      include_tasks: ../tasks/setup_dhcp_server.yml

    - name: Setup the packet filtering
      include_tasks: ../tasks/setup_packet_filter.yml
      
    - name: Setup the dhcp client on the bridge interface
      include_tasks: ../tasks/setup_dhcp_client.yml
      
    - name : Remove the default route
      include_tasks: ../tasks/setup_default_gateway.yml
      


  handlers:
    - name: enable dns server on reboot
      command: rcctl enable unbound
      
    - name: start the dns server
      command: rcctl start unbound

    - name: enable dhcp server on reboot
      command: rcctl enable dhcpd

    - name: start the dhcp server
      command: rcctl start dhcpd

    - name: apply changes to pf
      command: pfctl -f /etc/pf.conf

    - name: enable pf at boot
      command: pfctl -e
      ignore_errors: true

    - name: restart the network service
      command: sh /etc/netstart