- hosts: all
  become: yes
  
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    containerd_device: "/dev/sdb"
    containerd_mount_point: "/var/lib/containerd-storage"
    containerd_original: "/var/lib/containerd"

    # Application deployment variables
    docker_registry_user: "skuuun"
    frontend_image_name: "t-nsa-frontend"
    frontend_image_tag: "latest"

  tasks:
    - name: Remove docker install
      include_tasks: ../tasks/remove_docker.yml

    - name: Install CENTOS utils
      include_tasks: ../tasks/install_CENTOS_utils.yml

    - name: Configure containerd
      include_tasks: ../tasks/configure_containerd.yml

    - name: Install Kubernetes
      include_tasks: ../tasks/install_k8s_centos.yml

    - name: Join cluster
      include_tasks: ../tasks/join_cluster.yml

    - name: Pull frontend image
      include_tasks: ../tasks/pull_frontend_image.yml