#Gitea configuration with control-plane tolerations
gitea:
  admin:
    username: gitea_admin
    password: r8sA8CPHD9!bt6d
    email: "gitea@local.domain"
    passwordMode: keepUpdated

  config:
    database:
      DB_TYPE: postgres
      HOST: 192.168.2.12:5432
      NAME: gitea
      USER: gitea
      PASSWD: your_postgresql_password_here
      SSL_MODE: disable

    server:
      SSH_PORT: 22
      SSH_LISTEN_PORT: 2222

# Add tolerations to allow scheduling on control-plane node
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

# Make service accessible via NodePort
service:
  http:
    type: NodePort
    port: 3000
    nodePort: 30080

# Disable built-in PostgreSQL
postgresql:
  enabled: false

postgresql-ha:
  enabled: false

# Disable Redis/Valkey
valkey:
  enabled: false

valkey-cluster:
  enabled: false