- name: Install utils
  shell: yum install -y {{ item }}
  loop:
    - curl
    - iputils
    - bind-utils
    - strace
    - telnet
  register: utils_install
  changed_when: "'Nothing to do' not in utils_install.stdout"