- name: Download with curl
  get_url:
    url: https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
    dest: /tmp/kubectl
    mode: '0755'

- name: Install kubectl
  become: yes
  shell: |
    install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl