- name: Install cert manager CRDs
  shell: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.crds.yaml

- name: Copy certmanager configuration files
  ansible.builtin.copy:
    src: "../ressources/k8s/certmanager/"
    dest: "/root/.kube/ressources/certmanager/"
    mode: '0644'
    backup: yes

- name: Install helm jetstack repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Check if Jetstack release exists
  kubernetes.core.helm_info:
    name: cert-manager
    namespace: jetstack
  register: cert_manager_release_info
  ignore_errors: true

- name: Install Certmanager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    namespace: cert-manager
    create_namespace: true
    values_files:
      - /root/.kube/ressources/certmanager/helm/cert-manager-values.yml
  when: cert_manager_release_info.status is undefined or cert_manager_release_info.status.status != "deployed"

- name: Apply all cert-manager resources from directory
  shell: kubectl apply -f /root/.kube/ressources/certmanager/ 
  register: kubectl_apply_result
  changed_when: "'configured' in kubectl_apply_result.stdout or 'created' in kubectl_apply_result.stdout"
  failed_when:  
    - kubectl_apply_result.rc != 0
    - "'no objects passed to apply' not in kubectl_apply_result.stderr"