- name: Check if helm is already installed
  stat:
    path: /usr/local/bin/helm
  register: helm_installed

- name: Download Helm installation script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'
  when: not helm_installed.stat.exists

- name: Install Helm using official script
  shell: /tmp/get_helm.sh
  when: not helm_installed.stat.exists
  register: helm_install_result

- name: Clean up installation script
  file:
    path: /tmp/get_helm.sh
    state: absent
  when: not helm_installed.stat.exists

- name: Verify Helm installation
  shell: helm version --short
  register: helm_version_output
  changed_when: false

- name: Display Helm version
  debug:
    var: helm_version_output.stdout

- name: Initialize Helm repositories
  shell: |
    helm repo add stable https://charts.helm.sh/stable
    helm repo update
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: not helm_installed.stat.exists
  register: helm_repo_init
  changed_when: "'already exists' not in helm_repo_init.stderr"