- name: Run network setup script
  shell: ../scripts/network_setup.sh
  register: network_setup
  changed_when: false
  delegate_to: localhost
  become: no
  vars:
    ansible_python_interpreter: /usr/bin/python

- name: Show generated IP
  debug:
    msg: "Generated IP: {{ network_setup.stdout }}"

- name: Configure network interface with the generated IP
  ansible.builtin.command: ifconfig em3 {{ target_ip }} netmask {{ host_netmask }} up

- name: Set the hostname with the generated ip
  ansible.builtin.command: echo "inet {{ target_ip }} netmask {{ host_netmask }}" > /etc/hostname.em3