- name: Check if Google.com is reachable
  ansible.builtin.wait_for:
    host: google.com
    port: 80
    timeout: 5  
  ignore_errors: yes
  register: connectivity_check
  become: no

- name: Run network setup if Google is unreachable
  block:
    - name: Run network setup script
      shell: ../scripts/network_setup.sh
      register: network_setup
      changed_when: false
      delegate_to: localhost
      become: no
      vars:
        ansible_python_interpreter: /usr/bin/python

    - name: Show generated IP
      debug:
        msg: "Generated IP: {{ network_setup.stdout }}"

    - name: Extract target IP
      set_fact:
        target_ip: "{{ network_setup.stdout }}"

    - name: Configure network interface
      ansible.builtin.command: ifconfig em3 {{ target_ip }} netmask {{ host_netmask }} up

    - name: Persist network configuration
      ansible.builtin.command: echo "inet {{ target_ip }} netmask {{ host_netmask }}" > /etc/hostname.em3
      
  when: connectivity_check is failed 