version: '3'
services:
  api:
    container_name: dev_api
    image: sample-express-app
    build: .
    restart: always
    environment:
      DB_HOST: 192.168.2.12
      DB_TYPE: postgresql
      DB_PORT: 5432
      DB_USER: myapp_user
      DB_PASSWORD: SecurePassword123!
      DB_NAME: myapp_db
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge