# Gitea Helm Values - Updated for your infrastructure with proper database config
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# Deploy to backend_server node specifically
nodeSelector:
  kubernetes.io/hostname: backendserver

# Resource configuration
replicaCount: 1

strategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: "100%"
    maxUnavailable: 0

# Image configuration
image:
  registry: "docker.gitea.com"
  repository: gitea
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent
  rootless: true

# Security context for rootless image
podSecurityContext:
  fsGroup: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

# Service configuration
service:
  http:
    type: ClusterIP
    port: 3000
    clusterIP: None
  ssh:
    type: ClusterIP
    port: 22
    clusterIP: None

# Ingress disabled for now
ingress:
  enabled: false

# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Persistence configuration
persistence:
  enabled: true
  create: true
  mount: true
  claimName: gitea-shared-storage
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ""
  annotations:
    helm.sh/resource-policy: keep

# Gitea configuration
gitea:
  admin:
    username: gitea_admin
    password: r8sA8CPHD9!bt6d
    email: "gitea@local.domain"
    passwordMode: keepUpdated

  config:
    # Server configuration
    server:
      SSH_PORT: 22
      SSH_LISTEN_PORT: 2222  # For rootless image
      HTTP_PORT: 3000
      ROOT_URL: "http://gitea.local:3000"
      DISABLE_SSH: false

    # Database configuration - Connect to external PostgreSQL database_server
    database:
      DB_TYPE: postgres
      HOST: "192.168.2.12:5432"  # Your database_server IP
      NAME: gitea
      USER: gitea
      PASSWD: gitea_secure_password_2024  # Updated to match the database setup
      SSL_MODE: disable

    # Cache configuration using Redis
    cache:
      ENABLED: true
      ADAPTER: redis
      HOST: "redis://gitea-valkey-master:6379/0"

    # Session configuration
    session:
      PROVIDER: redis
      PROVIDER_CONFIG: "network=tcp,addr=gitea-valkey-master:6379,db=1"

    # Security settings
    security:
      INSTALL_LOCK: true
      SECRET_KEY: "your-secret-key-change-this-in-production"
      INTERNAL_TOKEN: "your-internal-token-change-this-in-production"

    # Repository settings
    repository:
      ROOT: "/data/git/repositories"
      DEFAULT_BRANCH: main

    # Indexer settings
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true

# Enable Redis for caching and sessions
valkey:
  enabled: true
  architecture: standalone
  global:
    valkey:
      password: changeme
  master:
    count: 1
    service:
      ports:
        valkey: 6379

# Disable built-in PostgreSQL since we're using external MySQL database
postgresql:
  enabled: false

postgresql-ha:
  enabled: false

# Monitoring
metrics:
  enabled: false
  serviceMonitor:
    enabled: false